# Generated by Django 3.0.3 on 2020-04-29 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
                ('department_head', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(null=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('year', models.CharField(choices=[('1', 'FIRSTYEAR'), ('2', 'SECONDYEAR'), ('3', 'THIRDYEAR'), ('4', 'FORTHYEAR')], max_length=1, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('confirmpassword', models.CharField(max_length=30, null=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['rollno'],
            },
        ),
        migrations.CreateModel(
            name='SubjectDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyid', models.IntegerField(null=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30, null=True)),
                ('confirmpassword', models.CharField(max_length=30, null=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('year', models.CharField(choices=[('1', 'FIRSTYEAR'), ('2', 'SECONDYEAR'), ('3', 'THIRDYEAR'), ('4', 'FORTHYEAR')], max_length=1, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.DepartmentDatabase')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.SubjectDatabase')),
            ],
        ),
    ]
