# Generated by Django 3.0.6 on 2020-05-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
                ('department_head', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='FacultyDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyid', models.IntegerField(null=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30, null=True)),
                ('confirmpassword', models.CharField(max_length=30, null=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('year', models.CharField(choices=[('1', 'FIRSTYEAR'), ('2', 'SECONDYEAR'), ('3', 'THIRDYEAR'), ('4', 'FORTHYEAR')], max_length=1, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.DepartmentDatabase')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(null=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('year', models.CharField(choices=[('1', 'FIRSTYEAR'), ('2', 'SECONDYEAR'), ('3', 'THIRDYEAR'), ('4', 'FORTHYEAR')], max_length=1, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('confirmpassword', models.CharField(max_length=30, null=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('admission_year', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.DepartmentDatabase')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['rollno'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_students', models.IntegerField(blank=True, default=0, null=True)),
                ('total_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.FacultyDatabase')),
            ],
            options={
                'db_table': 'feedback)_form',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=1000)),
                ('total_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.FeedbackForm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.StudentRegistration')),
            ],
            options={
                'db_table': 'answers',
                'ordering': ['updated_at'],
            },
        ),
        migrations.AddField(
            model_name='facultydatabase',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.SubjectDatabase'),
        ),
    ]
