# Generated by Django 3.0.3 on 2020-04-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departmentdatabase',
            table='department',
        ),
        migrations.AlterModelTable(
            name='subjectdatabase',
            table='subject',
        ),
    ]
