# Generated by Django 3.0.3 on 2020-05-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackprojectapp', '0002_auto_20200430_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'SECONDYEAR'), (3, 'THIRDYEAR'), (4, 'FORTHYEAR')])),
                ('questions', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question',
                'ordering': ['updated_at'],
            },
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.DepartmentDatabase'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.FacultyDatabase')),
                ('questions', models.ManyToManyField(to='feedbackprojectapp.Questions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.StudentRegistration')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.Feedback')),
            ],
            options={
                'db_table': 'answer',
                'ordering': ['updated_at'],
            },
        ),
    ]
