# Generated by Django 3.0.3 on 2020-05-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackprojectapp', '0003_auto_20200514_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.DepartmentDatabase'),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.SubjectDatabase'),
        ),
    ]
