# Generated by Django 3.0.3 on 2020-05-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackprojectapp', '0003_auto_20200501_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedbackprojectapp.StudentRegistration'),
            preserve_default=False,
        ),
    ]
