# Generated by Django 3.0.3 on 2020-05-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackprojectapp', '0005_auto_20200515_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='year',
            field=models.CharField(choices=[('1', 'FIRSTYEAR'), ('2', 'SECONDYEAR'), ('3', 'THIRDYEAR'), ('4', 'FORTHYEAR')], max_length=1, null=True),
        ),
    ]
