# Generated by Django 3.0.3 on 2020-05-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackprojectapp', '0006_feedbackform_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultydatabase',
            name='year',
        ),
    ]
